### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by cbfranca** [vanilla-masker/vanilla-masker#96]
rock-input → (master) $ bower install vanilla-masker --save --verbose
bower vanilla-masker#\*      not-cached https://github.com/BankFacil/vanilla-mask                                         er.git#*
bower vanilla-masker#\*         resolve https://github.com/BankFacil/vanilla-mask                                         er.git#*
bower vanilla-masker#\*        checkout 1.1.0
bower vanilla-masker#\*         ECMDERR Failed to execute "git clone https://github.com/BankFacil/vanilla-masker.git -b 1 .1.0 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objects: 24, done.         remote:  remote: Compressing objects: 100% (22/22), done.         remote: Total 24 (delta 1), reused 10 (delta 1), pack-reused 0          Note: checking out '85a63e0e9c9e22a92e8bb5430d948001183ba6e2'.  You are in 'detached HEAD' state. You can look a round, make experimental changes and commit them, and you can discard any commits you make in this state without impacti ng any branches by performing another checkout.  If you want to create a new branch to retain commits you create, you ma y do so (now or later) by using -b with the checkout command again. Example:    git checkout -b <new-branch-name>  fatal : cannot create directory at 'bankfacil:vanilla-masker': Invalid argument warning: Clone succeeded, but checkout failed.  You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Additional error details:
Cloning into '.'...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24 (delta 1), reused 10 (delta 1), pack-reused 0
Note: checking out '85a63e0e9c9e22a92e8bb5430d948001183ba6e2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

fatal: cannot create directory at 'bankfacil:vanilla-masker': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Stack trace:
Error: Failed to execute "git clone https://github.com/BankFacil/vanilla-masker.git -b 1.1.0 --progress . --depth 1", ex it code of #128
Cloning into '.'...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24 (delta 1), reused 10 (delta 1), pack-reused 0
Note: checking out '85a63e0e9c9e22a92e8bb5430d948001183ba6e2'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
fatal: cannot create directory at 'bankfacil:vanilla-masker': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
    at createError (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at ChildProcess.<anonymous> (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:102:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at executeCmd (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:61:22)
    at PThrottler._processEntry (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\p-throttler\inde x.js:89:25)
    at Promise.apply (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\p-throttler\node_modules\q\ q.js:1122:26)
    at Promise.promise.promiseDispatch (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\p-throttl er\node_modules\q\q.js:752:41)
    at C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\p-throttler\node_modules\q\q.js:1337:14
    at flush (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\p-throttler\node_modules\q\q.js:108 :17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Console trace:
Error
    at StandardRenderer.error (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:8 1:37)
    at Logger.<anonymous> (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29 :39)
    at C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\cleid\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:78 8:41)
System info:
Bower version: 1.7.9
Node version: 6.2.2
OS: Windows_NT 10.0.14393 x64

**Comment by QuentinFchx** [comment]
Might be related to #91

**Comment by fernandofleury** [comment]
@cbfranca can you try using the `1.1` version?

**Comment by rdiego26** [comment]
@cbfranca 
This issue still open ?
Has orientation from @fernandofleury  helped?

**Comment by fernandofleury** [comment]
I think the best course of action (if possible) is migrate to npm. Bower is not recommended nowadays.
